### ISSUE TITLE
RouteObserverMixin with StateNotifier

### ISSUE THREAD

**Issue by daisuke310vvv** [mono0926/route_observer_mixin#2]
Hi @mono0926, thank you for this awesome package. I'm very impressed with `route_observer_mixin`!

BTW, I'd like to use this with [state_notifier](https://pub.dev/packages/state_notifier) and want to handle all events in my class extends StateNotifier, but got an error like `'RouteObserverMixin<StatefulWidget>' can't be mixed onto 'StateNotifier<MyState>' because 'StateNotifier<MyState>' doesn't implement 'State<StatefulWidget>'`. Actually I understand this error, but do you have any ideas or samples for like this situations?

I'd appreciate it if you could reply.
Thank you.

**Comment by mono0926** [comment]
Thanks!

`RouteObserverMixin` is used in combination with `StatefulWidget`'s `State`, not `StateNotifier` as written this example: https://github.com/mono0926/route_observer_mixin/blob/79c2fbfdcdac042f175a51d5417ede863b764ae8/example/lib/pages/a_page.dart#L17

But I also think it is convenient to access RouteAware event in `StateNotifier`, so I added that feature just now 👍 
This should solve your situations.

> Add RouteAwareProvider, which offers RouteAwareEvent stream
> https://pub.dev/packages/route_observer_mixin#120

I rewrote BPage example by using RouteAwareProvider:
https://github.com/mono0926/route_observer_mixin/blob/master/example/lib/pages/b_page.dart

**Comment by mono0926** [comment]
@daisuke310vvv 

Thanks!

`RouteObserverMixin` is used in combination with `StatefulWidget`'s `State`, not `StateNotifier` as written this example: https://github.com/mono0926/route_observer_mixin/blob/79c2fbfdcdac042f175a51d5417ede863b764ae8/example/lib/pages/a_page.dart#L17

But I also think it is convenient to access RouteAware event in `StateNotifier`, so I added that feature just now 👍 
This should solve your situations.

> Add RouteAwareProvider, which offers RouteAwareEvent stream
> https://pub.dev/packages/route_observer_mixin#120

I rewrote BPage example by using RouteAwareProvider:
https://github.com/mono0926/route_observer_mixin/blob/master/example/lib/pages/b_page.dart

**Comment by daisuke310vvv** [comment]
@mono0926 
Thank you for your fast reply and adding new feature for this situation!
I really appreciate it!
