### ISSUE TITLE
[Question] Can we use this mixin to get the current route?

### ISSUE THREAD

**Issue by aytunch** [mono0926/route_observer_mixin#5]
From anywhere in the app, I would like to call:
`currentPath = Provider<RouteObserver>.of(context).getCurrentRoutePath;`
Is something like above possible?
Thanks.

**Comment by mono0926** [comment]
Added that kind of sample: https://github.com/mono0926/route_observer_mixin/blob/7cff4949f20a7bb8ad33a8351802222f1ab4f9d0/example/lib/pages/b_page.dart#L61-L63
